#!/bin/bash
set -e

WEB_HOME="/var/lib/webapp-core"
SRV_HOME="/srv/www"
APP=$1

if [ ! -d $SRV_HOME/$APP ]; then
    echo "I don't see $SRV_HOME/$APP"
    exit 2
fi

echo "Now setting up the basics for $APP. Cool? Hit enter."
read foo

cd $WEB_HOME

if [ ! -d envs ]; then
    mkdir envs
fi
if [ ! -d socks ]; then
    mkdir socks
fi
if [ ! -d logs ]; then
    mkdir logs
fi
cd envs

virtualenv $APP

source $WEB_HOME/envs/$APP/bin/activate
cd $SRV_HOME/$APP
if [ -e requirements.txt ]; then
    pip install -r requirements.txt
fi
cd $SRV_HOME/$APP/

WORKDIR=/tmp/$$/webapp-core
mkdir $WORKDIR -p
#mkdir $WORKDIR/build
#mkdir $WORKDIR/egg-info
#PYTHONPATH=/tmp/lib \
#    python setup.py \
#        build --build-base $WORKDIR/build \
#        egg_info --egg-base $WORKDIR/egg-info \
#        install

cd $WORKDIR
cp $SRV_HOME/$APP . -r --no-preserve=ownership
cd $APP
pwd
python setup.py install
cd $SRV_HOME
rm -rf $WORKDIR
