#!/bin/bash
set -e

WEB_HOME="/var/lib/webapp-core"
SRV_HOME="/srv/www"
APP=$1

if [ ! -d $SRV_HOME/$APP ]; then
    echo "I don't see $SRV_HOME/$APP"
    exit 2
fi

echo "Now setting up the basics for $APP. Cool? Hit enter."
read foo

cd $WEB_HOME

if [ ! -d envs ]; then
    mkdir envs
fi
cd envs

virtualenv $APP

source $WEB_HOME/envs/$APP/bin/activate
cd $SRV_HOME/$APP
if [ -e requirements.txt ]; then
    pip install -r requirements.txt
fi
python $SRV_HOME/$APP/setup.py install
