#!/bin/bash

WEB_HOME="/var/lib/webapp-core"
SRV_HOME="/srv/www"

if [ $UID != 0 ]; then
    echo "please invoke as root"
    exit 1
fi
su webapp-core

APP=$1

if [ ! -d $SRV_HOME/$APP ]; then
    echo "I don't see $SRV_HOME/$APP. Install the app."
    exit 2
fi

if [ ! -d $WEB_HOME/envs/$APP ]; then
    echo "I don't see $WEB_HOME/envs/$APP"
    echo "  - run webapp-core-setup $APP"
    exit 3
fi

source $WEB_HOME/envs/$APP/bin/activate

